### Api User Login
POST http://localhost:4000/api/user/login
Content-Type: application/json

{
    "email": "JANE@EXAMPLE.COM",
    "password": "Jane123@"
}

### Api User Register
POST http://localhost:4000/api/user/register
Content-Type: application/json

{
    "name": "JANE",
    "email": "JANE@example.com",
    "password": "Jane123@"
}
