### POST User Login
POST http://localhost:4000/api/user/login
Content-Type: application/json

{
    "email": "JOHN@EXAMPLE.COM",
    "password": "John123@"
}

### POST User Register
POST http://localhost:4000/api/user/register
Content-Type: application/json

{
    "name": "JANE",
    "email": "JANE@example.com",
    "password": "Jane123@"
}

### GET User Profile
GET http://localhost:4000/api/user/profile
Authorization: Bearer 